project:
  type: website
  output-dir: doc

website:
  title: "Tyler Hansen Portfolio"
  navbar:
    right:
      - about.qmd
      - text: "Resume"
        href: posts/Resume.qmd
      - text: "Cover Letter"
        href: posts/CoverLetter.qmd
      - icon: github
        href: https://github.com/tyhansen751
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual