project:
  type: website
  output-dir: docs

website:
  title: "Tyler Hansen Portfolio"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: Resume.qmd
        text: Resume
      - href: CoverLetter.qmd
        text: Cover Letter
      - icon: github
        href: https://github.com/tyhansen751

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual
